# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skycast_app', '0002_auto_20171224_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='search',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
