# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skycast_app', '0004_auto_20171224_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='long',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='search',
            name='zip',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
