# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skycast_app', '0005_auto_20171225_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='zip',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
