# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skycast_app', '0007_auto_20171225_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='locationFriendlyName',
        ),
        migrations.AddField(
            model_name='search',
            name='location_Search',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
